export const env = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  ABACATE_PAY_API_URL: process.env.NEXT_PUBLIC_ABACATE_PAY_API_URL,
  ABACATE_PAY_API_KEY: process.env.ABACATE_PAY_API_KEY,
  ABACATE_WEBHOOK_SECRET: process.env.ABACATE_WEBHOOK_SECRET,
  NEXT_PUBLIC_ABACATE_PAY_PUBLIC_KEY:
    process.env.NEXT_PUBLIC_ABACATE_PAY_PUBLIC_KEY,
};
